title: Liyuan's Log
# remote_theme: pages-themes/cayman@v0.2.0
theme: jekyll-theme-cayman
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
markdown: kramdown
kramdown:
  math_engine: mathjax
